service: integration-template-azure

provider:
  name: azure
  location: West US
  stage: dev

package:
  exclude:
    - .gitignore
    - package.json
    - README.md
    - .git/**

functions:
  webhook:
    handler: src/handlers.webhook
    description: 'Webhook payload endpoint'
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: webhook
          authLevel: anonymous
  verify:
    handler: src/handlers.verify
    description: 'Webhook verification endpoint'
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: webhook
          authLevel: anonymous
